package sw

import (
	"github.com/flostadler/name-generator/pkg/randomizer"
)

var(
	characters = [...] string {
		"Darth Sidious",
		"Ahsoka Tano",
		"Rey Skywalker",
		"Chelli Lona Aphra",
		"Tam Posla",
		"Darth Momin",
		"Darth Maul",
		"Wolf Sazen",
		"Leia Organa Solo",
		"Darth Krayt",
		"Ronen Tagge",
		"Beilert Valance",
		"Bevel Lemelisk",
		"Vernestra Rwoh",
        "Avar Kriss",
        "Bell Zettifar",
        "Lina Soh",
        "Sskeer",
        "Burryaga Agaburry",
        "Leox Gyasi",
        "Ady Sun'Zee",
        "Ty Yorrick",
        "Zallah Macri",
        "Porter Engle",
        "Luke Skywalker",
        "Anakin Skywalker",
        "Han Solo",
        "Chewbacca",
        "Leia Organa",
        "C-3PO",
        "R2-D2",
        "Owen Lars",
        "Beru Whitesun Lars",
        "Wilhuff Tarkin",
        "Obi-Wan Kenobi",
        "Lando Calrissian",
        "Mas Amedda",
        "Padmé Amidala",
        "Cassian Andor",
        "The Armorer",
        "Colton Raymus Antilles",
        "Wedge Antilles",
        "Ryder Azadi",
        "Azmorigan",
        "Ponda Baba",
        "Cad Bane",
        "Darth Bane",
        "Tobias Beckett",
        "Val Beckett",
        "The Bendu",
        "Sio Bibble",
        "Depa Billaba",
        "Jar Jar Binks",
        "Zorii Bliss",
        "Lux Bonteri",
        "Bossk",
        "Ezra Bridger",
        "Bix Caleen",
        "Cid",
        "Rush Clovis",
        "Kaydel Ko Connix",
        "Eno Cordova",
        "Salacious B. Crumb",
        "Commander CC-2224 \"Cody\"",
        "CT-9904 \"Crosshair\"",
        "Figrin D'an",
        "Poe Dameron",
        "Biggs Darklighter",
        "The Daughter",
        "Mee Deechi",
        "Dengar",
        "DJ",
        "Din Djarin",
        "Tan Divo",
        "Lott Dod",
        "Jan Dodonna",
        "Count Dooku",
        "Darth Tyranus",
        "Cin Drallig",
        "Garven Dreis",
        "Kanan Jarrus",
        "Caleb Dume",
        "Cara Dune",
        "Rio Durant",
        "Tala Durith",
        "CT-1409 \"Echo\"",
        "The Eighth Brother",
        "Morgan Elsbeth",
        "Embo",
        "Galen Erso",
        "Jyn Erso",
        "Cornelius Evazan",
        "Onaconda Farr",
        "Boba Fett",
        "Jango Fett",
        "FN-2187 - Finn",
        "Kit Fisto",
        "CT-27-5555 \"Fives\"",
        "Bib Fortuna",
        "Babu Frik",
        "Garsa Fwip",
        "Adi Gallia",
        "Garindan",
        "Saw Gerrera",
        "Steela Gerrera",
        "Moff Gideon",
        "The Grand Inquisitor",
        "Commander CC-1004 \"Gree\"",
        "Greedo",
        "Captain CC-5576-39 \"Gregor\"",
        "Grievous",
        "Grogu",
        "Nute Gunray",
        "Rune Haako",
        "Valin Hess",
        "Amilyn Holdo",
        "Armitage Hux",
        "Chirrut Îmwe",
        "Jabba the Hutt",
        "Jannah",
        "CT-5597 \"Jesse\"",
        "Dexter Jettster",
        "Tiaan Jerjerrod",
        "Qui-Gon Jinn",
        "Cere Junda",
	}
)

func Generate() string {
	return randomizer.GetRandom(characters[:])
}

func GenerateMultiple(count int) []string {
	s := make([]string, count)
	for i := 0;  i <= count; i++ {
		s[i] = Generate()
	}

	return s
}
